### ISSUE TITLE
Typecho 安装之后无法播放

### ISSUE THREAD

**Issue by liqifu** [shingchi/Remix#2]
三个版本都有尝试过：
 1. Remix_v2.1.0.zip 此版本可以启用，界面以显示，但是无法播放，点不动，一直只有 歌曲 - 艺术家
 2. Remix_v2.1.1.tar 这个版本解压之后，文件都在 Plugin/ 目录下，把文件放入 Remix 文件夹之后，可以显示界面，但是仍然无法播放
 3. Remix-master.zip 这个版本解压之后，文件在 Plugin/Remix-master/ 目录下，但是插件无法启用，显示 500 错误

 - 前面两个安装包是在 Typecho 官方论坛下载的，最后的是 github
 - 主机：aliyun ECS 装了 memcache Curl enabled 插件设置就是默认值，没有更改

**Comment by shingchi** [comment]
不管是哪个版本都应该都是放在 `Plugin/Remix` 下，建议下载 master 版来覆盖一下，然后可以选择文件式的缓存测试看看，有什么问题再反馈，谢谢！

**Comment by liqifu** [comment]
嗯。刚刚又重新覆盖试了。所有版本是都可以启用的，界面都有。文件式也选择尝试过，还是点不动。
![20150224234055](https://cloud.githubusercontent.com/assets/11178072/6352574/a11a3f7a-bc7e-11e4-8a16-e59613572063.png)

**Comment by 1995LZH** [comment]
我本地测试和博客上测试是无法播放的，看见你的演示站和博客都可以正常播放，看来是我使用方法不当导致的。建议您完善一下readme.md文件，将具体的信息及使用方法写清楚。谢谢

**Comment by 1995LZH** [comment]
（刚才回复错人了，真尴尬）针对你说的第三种情况，请将Plugin/Remix-master/ 目录改为Plugin/Remix/ 目录，这样就不会500了

**Comment by shingchi** [comment]
@liqifu @1995LZH 能发下你播放页面的地址么？

**Comment by liqifu** [comment]
@shingchi http://beta.liqifu.cn/start-page

**Comment by 1995LZH** [comment]
@shingchi 我的播放页 http://www.hello1995.com/index.php/info.html 

我咨询过主机商，我用的主机支持cURL。并且，为了确保有写入权限，我将Remix文件夹权限设置为777。

**Comment by shingchi** [comment]
@liqifu @1995LZH 我看了下你们的页面，你们的问题应该都一样，你们的 action 页面都打不开，获取不到请求结果，所以音乐没法正常播放。可以看下你们是否完整的上传 action 文件，还有就是 rewrite 有没有开启，设置有没有正确。

**Comment by liqifu** [comment]
@shingchi 我的页面改了，麻烦重新帮我看看。另外，action 页面能不能打开是怎么看到的。rewrite 需要怎么设置才是正确的？

**Comment by liqifu** [comment]
@shingchi 貌似确实是 Action.php 这个网页有问题。
我的 http://bbc.liqifu.cn/usr/plugins/Remix/Action.php 这个打开之后，出现错误提示

Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM, expecting T_VARIABLE in /www/web/bbc/public_html/usr/plugins/Remix/Action.php on line 44

你的
http://shingchi.coding.io/usr/plugins/Remix/Action.php
http://lcz.me/usr/plugins/Remix/Action.php
打开都没提示。

你可以重新传一下你的那个 Action.php 吗

**Comment by liqifu** [comment]
@shingchi 貌似确实是 Action.php 这个网页有问题。
我的 http://bbc.liqifu.cn/usr/plugins/Remix/Action.php 这个打开之后，出现错误提示

Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM, expecting T_VARIABLE in /www/web/bbc/public_html/usr/plugins/Remix/Action.php on line 44

你的
http://shingchi.coding.io/usr/plugins/Remix/Action.php
http://lcz.me/usr/plugins/Remix/Action.php
打开都没提示。

你可以重新传一下你的那个 Action.php 吗

**Comment by 1995LZH** [comment]
@shingchi  我的 rewrite 有正确开启。。。

**Comment by shingchi** [comment]
@liqifu 不是action文件的问题，你 action 访问的地址是 http://bbc.liqifu.cn/action/remix 但你的根本没法访问呢

**Comment by shingchi** [comment]
@1995LZH 你的也一样没法访问 http://www.hello1995.com/action/remix

**Comment by shingchi** [comment]
@liqifu @1995LZH 你们查看下数据库里，插件的配置有没有启用到 action？假如有的话，那就很可能是 rewrite 规则的问题了。

**Comment by liqifu** [comment]
@shingchi http://lcz.me/action/remix 你的显示 Bad Request! 要这样就是可以访问吗？

**Comment by liqifu** [comment]
怎么看数据库里有没有启用 action？

**Comment by shingchi** [comment]
@liqifu 嗯，这样才算正常访问，数据库里有个options表，里面找到插件配置字段。

**Comment by liqifu** [comment]
@shingchi 
remix的表里面是这样的
{s:9:"cacheMode";s:4:"file";s:9:"cacheHost";s:9:"127.0.0.1";s:9:"cachePort";s:5:"11211";s:4:"hash";s:12:"Remix_v2.0.0";}
我把它禁用了，重新试了文件式，还是不行。

**Comment by 1995LZH** [comment]
@shingchi 我的options表内，rewrite的值为1；plugin表内有关于remix的内容，其他的都没有和remix相关的信息。根目录下.htaccess的部分内容：
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]

哪里错了吗？

**Comment by shingchi** [comment]
@liqifu @1995LZH 可以让我登录下后台看看吗？

**Comment by liqifu** [comment]
@shingchi 没问题，早就想了。这个怎么私信？

**Comment by shingchi** [comment]
@liqifu Q119672000
